project-folder: "/scratch/project_2001881/201204_NB551722_0018_AH2HWGBGXF"
bcl-folder: "/scratch/project_2001881/201204_NB551722_0018_AH2HWGBGXF_results-bcl"
report-script: "/scratch/project_2001881/Pipeline-SequencingQC/scripts/workflow-report.Rmd"
pipeline-folder: "/scratch/project_2001881/Pipeline-SequencingQC/"
pipeline-config: "/scratch/project_2001881/Pipeline-SequencingQC/Pipeline-SequencingQC_config.yaml"
report-folder: "/scratch/project_2001881/201204_NB551722_0018_AH2HWGBGXF_QC-report"

###############################################################
#
# Input parameters
#
###############################################################

expected_reads_per_sample: 100000