project-folder: "/scratch/project_2001881/201204_NB551722_0018_AH2HWGBGXF"
pipeline-folder: "/scratch/project_2001881/Pipeline-SequencingQC"

###############################################################
#
# Input parameters
#
###############################################################

expected_reads_per_sample: 100000