project-folder: "/scratch/project_2001310/201110_NB551722_0016_AHYGMKBGXC"
pipeline-folder: "/scratch/project_2001310/Pipeline-SequencingQC"

###############################################################
#
# Input parameters
#
###############################################################

expected_reads_per_sample: 100000